version: "3"

dotenv:
  - "ficus.env"

tasks:
  setup:
    cmds:
      - podman-compose -f scripts/compose.yaml up
  cleanup:
    cmds:
      - podman rm -f $(podman ps -a | grep ficus_db | awk '{print $1}')
      - rm -rf ./scripts/data-dev/*
  vendor:
    cmds:
      - go mod tidy
      - go mod vendor
  build:
    cmds:
      - go build
  image:
    cmds:
      - docker build -t "$APP_AUTHOR/$APP:$APP_VERSION" -f dev-files/docker/Dockerfile
