version: "3"

dotenv:
  - "task.env"

tasks:
  mod:
    cmds:
      - go mod tidy
      - go mod vendor
  build:
    cmds:
      - go build
  image:
    cmds:
      - docker build -t "$AUTHOR/$APP:$VERSION" -f dev-files/docker/Dockerfile
