app:
  runtimeRootPath: runtime/
  logFileLocation: logs
  logFileSaveName: log
  logFileExt: log
  timeFormat: 2006-01-02 15:04:05
server:
  runMode: debug
  httpPort: 8090
  readTimeout: 60
  writeTimeout: 60
kafka:
  locations: [localhost:9092]