app:
  runtimeRootPath: runtime/
  logFileLocation: logs/
  logFileSaveName: log
  logFileExt: log
  timeFormat: 20060102
server:
  runMode: debug
  httpPort: 8090
  readTimeout: 60
  writeTimeout: 60
kafka:
  locations: [localhost:9092]