# ficus config
apiVersion: v1
kind: ConfigMap
metadata:
  name: ficus-config
  labels:
    app: ficus
data:
  application.yml: |
    app:
      runtimeRootPath: runtime
      logFileLocation: logs
      logFileSaveName: log
      logFileExt: log
      timeFormat: 20060102
    server:
      runMode: debug
      httpPort: 8090
      readTimeout: 60
      writeTimeout: 60
    kafka:
      locations: [ kafka-service:9092 ]
---
# ficus headless
apiVersion: v1
kind: Service
metadata:
  name: ficus-headless
  labels:
    app: ficus
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: ficus
      port: 8090
      targetPort: ficus
  selector:
    app: ficus
---
# ficus service
apiVersion: v1
kind: Service
metadata:
  name: ficus-service
  labels:
    app: ficus
spec:
  # using node port for local dev
  type: NodePort
  selector:
    app: ficus
  ports:
    - port: 8090
      targetPort: ficus
      nodePort: 30090
---
# ficus stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ficus
  labels:
    app: ficus
spec:
  serviceName: ficus-headless
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ficus
  template:
    metadata:
      labels:
        app: ficus
    spec:
      containers:
        - name: ficus
          image: azusachino/ficus:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: ficus
              containerPort: 8090
          volumeMounts:
            # Dockerfile workdir is /root
            - mountPath: /root/conf/
              name: ficus-conf
            - mountPath: /root/runtimme
              name: ficus-data
              subPath: logs
            - mountPath: /root/static
              name: ficus-data
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: ficus-conf
          configMap:
            name: ficus-config
  volumeClaimTemplates:
    - metadata:
        name: ficus-data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
