# pvc for kafka
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ficus
  name: kafka-pvc
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
# env for kafka
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ficus
  name: kafka-env
  labels:
    app: kafka
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://$(MY_POD_NAME).kafka-headless:9092
  ALLOW_PLAINTEXT_LISTENER: yes
  KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
  KAFKA_CFG_LOGS_DIRS: /opt/bitnami/kafka/data
  JMX_PORT: 9988
---
#部署 Service Headless，用于Kafka间相互通信
apiVersion: v1
kind: Service
metadata:
  namespace: ficus
  name: kafka-headless
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: none
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
  selector:
    app: kafka
---
#部署 Service，用于外部访问 Kafka
apiVersion: v1
kind: Service
metadata:
  namespace: ficus
  name: kafka-service
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ficus
  name: kafka-stateful
  labels:
    app: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:2.8.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-data
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: kafka-env
          ports:
            - name: kafka
              containerPort: 9092
          livenessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc