app:
  runtimeRootPath: runtime
  logFileLocation: logs
  logFileSaveName: log
  logFileExt: log
  timeFormat: 20060102
server:
  runMode: debug
  httpPort: 8090
  readTimeout: 60s
  writeTimeout: 60s
database:
  # dbType: postgres
  dbName: postgres
  dbUser: postgres
  dbPort: 5432
  tablePrefix: tb_
  charset: utf8
  maxIdleConns: 10
  maxOpenConns: 100
  sslMode: disable
# kafka:
#   locations:
#     - 127.0.0.1:9092
# grpc:
#   server: 127.0.0.1
#   port: 50051
# etcd:
#   endpoints:
#     - 127.0.0.1:2379
#   timeout: 60
